Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
    vb.linked_clone = true
  end

  config.vm.define "master" do |master|
    master.vm.box = "geerlingguy/ubuntu2004"
    master.vm.network :private_network, ip: "192.168.56.101"
    master.vm.hostname = "master.home"
  end

  config.vm.define "worker" do |worker|
    worker.vm.box = "geerlingguy/ubuntu2004"
    worker.vm.network :private_network, ip: "192.168.56.102"
    worker.vm.hostname = "worker.home"
  end

end
