---
- name: Install Docker with Ansible
  hosts: all
  become: True

  tasks:

    - name: Updating the system
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrading the system
      apt: upgrade=dist force_apt_get=yes

    - name: Installing aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Installing required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'python3-apt']

    - name: Adding Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/{{ansible_os_family|lower}}/gpg
        state: present

    - name: Add Docker Module Repository
      ansible.builtin.deb822_repository:
        name: docker
        types: [deb]
        uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
        signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        suites: ["{{ ansible_distribution_release | lower }}"]
        components: [stable]
        state: present
        enabled: yes

    - name: Updating apt and installing docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Copying Daemon File
      copy: src=./daemon.json dest=/etc/docker/daemon.json

    - name: Restarting Docker Service
      service: name=docker state=restarted

    - name: Adding vagrant user to docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes
