---
- name: Create Portainer Agent
  hosts: all
  become: True
  
  tasks:
    - name: Pull Portainer Agent container
      community.docker.docker_image:
        name: "portainer/agent:latest"
        source: pull
      
    - name: Create Portainer Agent container
      community.docker.docker_container:
        name: "portainer_agent"
        image: "portainer/agent:latest"
        ports:
          - 9001:9001
        volumes:
          - /var/lib/docker/volumes:/var/lib/docker/volumes
          - /var/run/docker.sock:/var/run/docker.sock
          - /:/host
        restart_policy: "always"
        detach: true